version: '3'
services:
  postgredb:
    image: postgres
    container_name: pgdb
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${PG_DATABASE:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-satya}
      POSTGRES_USER: ${PG_USER:-satya}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${PG_USER:-satya}" ]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true
    volumes:
      - my-data:/var/lib/postgresql/data/
volumes:
  my-data:
    driver: local
